const mv = document.querySelector("#mv");
const apr = document.querySelector("#apr");
const ele = document.querySelector("#ele");
const prod1 = document.querySelector(".prod1");
const prod1a = document.querySelector(".prod1a");
const prodtxt = document.querySelectorAll("div.prodtxt");
const prod = document.querySelector(".prod");
const ld = document.querySelector(".ld");
const newp = document.querySelector(".new");
const pr = document.querySelectorAll("h1.pr");
const prc = document.querySelector(".prc");
const com = document.querySelector(".com");
const txtp = document.querySelector(".txtp");
const prej = document.querySelector("#prej");
const vol = document.querySelector("#vol");
const dv = document.querySelector("#dv");
const nov = document.querySelector("#nov");
const sch = document.querySelector("#sch");
const myUL = document.querySelector("#myUL");
const myLI = document.querySelector("#myUL li");
const lg = document.querySelector(".lg");
const pr1 = document.querySelector("#pr1");
const desc = document.querySelector(".desc");
const img1 = document.querySelector("#img1");
const img2 = document.querySelector("#img2");
const img3 = document.querySelector("#img3");
const e1 = document.querySelector(".e1");
const e2 = document.querySelector(".e2");
const e3 = document.querySelector(".e3");
const e4 = document.querySelector(".e4");
const e5 = document.querySelector(".e5");
const exc = document.querySelector("#exc");
const exc2 = document.querySelector("#exc2");
const coment = document.querySelector("#coment");
const cbtn = document.querySelector("#cbtn");
const cts = document.querySelector(".cts");
const e1r = document.querySelector(".e1r");
const e2r = document.querySelector(".e2r");
const e3r = document.querySelector(".e3r");
const e4r = document.querySelector(".e4r");
const e5r = document.querySelector(".e5r");
const re = document.querySelector(".re");
const avv = document.querySelector(".avv");
const prn = document.querySelector("#prn");
const cpr = document.querySelector("#cpr");
const quant = document.querySelector("#quant");
const vd = document.querySelector(".vd");
const btnspv = document.querySelectorAll("div.btnspv");
const prox = document.querySelectorAll("button#prox");
const volt = document.querySelectorAll("button#volt");
const pimg = document.querySelectorAll("img#pimg");
const lin = document.querySelector("#lin");
const drop = document.querySelector(".drop");
const cad = document.querySelector(".cad");
const nmu = document.querySelector(".nmu");
const droplg = document.querySelector(".droplg");
const nusu = document.querySelector("#nusu");
const desl = document.querySelector("#desl");
const usu = document.querySelector("#usu");
const off = document.querySelector(".off");
const pro = document.querySelector(".pro");
const dsh = document.querySelectorAll("h1.dsh");
const descdsh = document.querySelector(".descdsh");
const img1i = document.querySelector("#img1 img");
const img2i = document.querySelector("#img2 img");
const img3i = document.querySelector("#img3 img");
const offtxt = document.querySelector("#offtxt");

let parc;
let txtc;
let cmtr;
let ctxt;
let cps;
let cc = 0;
let rate1;
let rate2;
let rate3;
let rate4;
let rate5;
let dt;
let nota = 0;
let notact = 0;
let vds = 0;
let sel = 0;
let selm = 0;
let sela = 0;
let sele = 0;
let seld = 0;
let seln = 0;
let esto;
let vendm = 5;
let venda = 3;
let otxt = "";

const prods = [prod1, prod1a];